export enum AuthEnum {
  USER_NAME = "USER_NAME",
  USER_PASS = 'USER_PASS',
  ACCOUNT_ID = 'ACCOUNT_ID',
  API_KEY_TOKEN = 'API_KEY_TOKEN',
  API_ACCESS_TOKEN = 'API_ACCESS_TOKEN',
  ALL_CREDENTIALS_SET = 'ALL_CREDENTIALS_SET'
}
